### ISSUE TITLE
typedValue always returns string instead of e.g. number or boolean etc.

### ISSUE THREAD

**Issue by rfe-css** [syncrea/ng-rfx#10]
When number is defined in the Form definitions, the value returned from the form state is still string when coming from an input.
typed-form-control.ts typedValue returns the value of FormControl without converting it to T. 
I guess since T probably cannot be determined.
Maybe one could define a converter in the form definition, which would be used to convert the string control value to whatever is needed?

**Comment by gionkunz** [comment]
Solved by introducing custom field definition type.

**Comment by gionkunz** [comment]
Solved by introducing custom field definition type.
