### ISSUE TITLE
ng-rfx v2.0.2: export type TypedFormControlInfer missing in index.ts

### ISSUE THREAD

**Issue by meck93** [syncrea/ng-rfx#27]
hi @gionkunz 

The newest version of the library v2.0.2 [(index.ts)](https://github.com/syncrea/ng-rfx/blob/aec63cadbc89d95b716aea4a97a73261b2d78832/libs/rfx-lib/src/index.ts) no longer exports the type `TypedFormControlInfer`. Is this on purpose? Since it is the return type of the `getForm()` method of the `FormRegistry` class, shouldn't it be exported too? At least, we used it to type a function return type with it. 

```
export declare class FormRegistry {
    getForm<T>(key: FormRegistryKey<T>): TypedFormControlInfer<T> | null;
}
```

thanks for your feedback!

**Update**
It can be imported but just from `import { TypedFormControlInfer } from 'ng-rfx/lib/model';`. Is this intended?

**Comment by gionkunz** [comment]
Hi @meck93 , no that's a "bug" in 2.0.2. The inference type should be exported from the public API / barrel file. I've fixed it and it will be published in 2.0.3. Thanks for the report!
