### ISSUE TITLE
Feature Request: clear / remove all forms from registry

### ISSUE THREAD

**Issue by rfe-css** [syncrea/ng-rfx#30]
We need to delete all registered forms without knowing the key.
It would be possible, to store all keys in state, but we don't need to, other than to be able to delete all registered forms. 
This would all not be necessary, if we had a method clearForms on the registry.
Should be a very easy addition too.

See PR: https://github.com/syncrea/ng-rfx/pull/31

**Comment by gionkunz** [comment]
Thanks for the PR Raphi! This will be part of the 2.0.3 release this weekend.
